spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/marketplace?autoreconnect=true"
    password: "bestuser"
    username: "bestuser"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/
    schemas: marketplace
    user: "bestuser"
    password: "bestuser"
server:
  port: 8080
  servlet:
    context-path: /
jwt:
  secret: asdgasdgfdrewerg
  jwtLifeTime: 36000000