server:
  port: 5555
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8080/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8090/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8180/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth
            - JwtAuthFilter
jwt:
  secret: 46294A404E635266556A586E327235753778214125442A472D4B615064536756